version: "3"
services:

  #
  # Frontend components
  #
  vote:
    image: registry.gitlab.com/crafteo/example-voting-app/vote
    ports:
      - 5000:80
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379"

  #
  # Middle components
  #
  worker:
    image: registry.gitlab.com/crafteo/example-voting-app/worker
    depends_on:
      - db
      - redis

  #
  # Backend components
  #
  result:
    image: registry.gitlab.com/crafteo/example-voting-app/result
    ports:
      - 5001:80
    depends_on:
      - db

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
