version: "3"
services:

  #
  # Frontend components
  #
  vote:
    image: registry.gitlab.com/crafteo/example-voting-app/vote
    ports:
      - 8080:80
    depends_on:
      - redis
    networks:
      - vote_net
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 50M

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - vote_net
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 20M

  #
  # Middle components
  #
  worker:
    image: registry.gitlab.com/crafteo/example-voting-app/worker
    depends_on:
      - db
      - redis
    networks:
      - vote_net
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 50M

  #
  # Backend components
  #
  result:
    image: registry.gitlab.com/crafteo/example-voting-app/result
    ports:
      - 8081:80
    depends_on:
      - db
    networks:
      - vote_net
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 50M

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - vote_net
    deploy:
      resources:
        reservations:
          cpus: '0.05'
          memory: 50M

volumes:
  db-data:

networks:
  vote_net:
    driver: overlay
