# Using official python runtime base image
FROM python:2.7-alpine

# Set the application directory
WORKDIR /app

# Copy source code 
ADD . /app

# install dependencies
RUN pip install -r requirements.txt

# Define our command to be run when launching the container
CMD ["gunicorn", "app:app", "-b", "0.0.0.0:80", "--log-file", "-", "--access-logfile", "-", "--workers", "4", "--keep-alive", "0"]
