version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
    - "discovery.type=single-node"
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
    - 8091:9200
    - 8092:9300

  kibana:
    image: kibana:7.7.0
    ports:
    - 8082:5601
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.7.0
    ports:
    - 8089:8089
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch