version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
    - "discovery.type=single-node"
    ports:
    - 9200:9200
    - 9300:9300

  kibana:
    image: kibana:7.7.0
    ports:
    - 5601:5601
    depends_on:
      - elasticsearch

  logstash:
    image: logstash:7.7.0
    ports:
    - 9600:9600
    - 8089:8089
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
    depends_on:
      - elasticsearch
