version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      resources:
        reservations:
          cpus: '0.05'
          memory: 50M

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    ports:
      - "8085:9000"
      - "8086:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
    deploy:
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          cpus: '0.05'
          memory: 50M


networks:
  agent_network:
    driver: overlay
    attachable: true

volumes:
  portainer_data:
