version: '3.2'

services:
  portainer:
    image: portainer/portainer-ce:2.11.0
    ports:
      - "8085:8000"
      - "8086:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      
volumes:
  portainer_data:
